In [22]:
from __future__ import division
from __future__ import print_function

import numpy as np
import math
import time
import argparse

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from sklearn import metrics
from matplotlib import pyplot as plt

from utils import load_data2, accuracy
from model.models import GCN

plt.rcParams['font.sans-serif'] = ['SimHei']  # 用来正确显示中文标签
plt.rcParams['font.serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False  # 用来正确显示负号




adj, features, labels, idx_train, idx_val, idx_test = load_data2()

print('01_OK')

Loading 1 dataset...
(20774, 2)
labels: tensor([3, 0, 0,  ..., 0, 0, 0])
features tensor([[-0.1469,  0.0886, -0.1448,  ...,  0.2986, -0.0217, -0.1078],
        [-0.1469,  0.0531, -0.1447,  ...,  0.1480, -0.0582, -0.0195],
        [-0.1469,  0.1144, -0.1448,  ...,  0.2070, -0.0337, -0.0422],
        ...,
        [-0.1469,  0.1209, -0.1452,  ...,  0.2070, -0.0337, -0.0422],
        [-0.1469,  0.0886, -0.1448,  ...,  0.2070, -0.0337, -0.0422],
        [-0.1501,  0.1338, -0.1449,  ...,  0.2070, -0.0337, -0.0422]])
01_OK


In [23]:
from model.LSTM import LSTM

model = LSTM(input_size=features.shape[1], output_size=4)
loss_function = nn.MSELoss()
optimizer = optim.Adam(model.parameters(),
                       lr=0.01, weight_decay=5e-4)
print(model)
print("---------------")
# print(features.shape[1])

print(labels.dtype)
print(features.shape)
print(features.shape[0])
result = []
for i in range(200):
    for j in range(features.shape[0]):
        t = time.time()
        model.train()
        optimizer.zero_grad()
        x= features[j]
        x = np.expand_dims(x, axis=0)
        # print(x.shape)
        x = np.expand_dims(x, axis=0)
        x = torch.Tensor(x)
        output = model(x)
        output = F.softmax(output, dim=0)
        # output = nn.Softmax(output, dim=1)
        # loss = loss_function(output, labels[j])
        # loss = F.nll_loss(output, labels[j])
        # loss.backward()
        # result.append(output)
        # loss_train = F.nll_loss(output[idx_train], labels[idx_train])
        # loss_train.backward()
        if j%2000 ==1:
            print(output)
        optimizer.step()

    # if i%25 == 1:
    #     print(f'epoch:{i:3} loss:{loss.item():10.8f}')

print(result)
print('02_ok')

LSTM(
  (layer1): LSTM(86, 64, num_layers=2)
  (layer2): Linear(in_features=64, out_features=4, bias=True)
)
---------------
torch.int64
torch.Size([5764, 86])
5764
tensor([[[1., 1., 1., 1.]]], grad_fn=<SoftmaxBackward>)
tensor([[[1., 1., 1., 1.]]], grad_fn=<SoftmaxBackward>)
tensor([[[1., 1., 1., 1.]]], grad_fn=<SoftmaxBackward>)
tensor([[[1., 1., 1., 1.]]], grad_fn=<SoftmaxBackward>)
tensor([[[1., 1., 1., 1.]]], grad_fn=<SoftmaxBackward>)
tensor([[[1., 1., 1., 1.]]], grad_fn=<SoftmaxBackward>)
tensor([[[1., 1., 1., 1.]]], grad_fn=<SoftmaxBackward>)
tensor([[[1., 1., 1., 1.]]], grad_fn=<SoftmaxBackward>)
tensor([[[1., 1., 1., 1.]]], grad_fn=<SoftmaxBackward>)
tensor([[[1., 1., 1., 1.]]], grad_fn=<SoftmaxBackward>)
tensor([[[1., 1., 1., 1.]]], grad_fn=<SoftmaxBackward>)
tensor([[[1., 1., 1., 1.]]], grad_fn=<SoftmaxBackward>)
tensor([[[1., 1., 1., 1.]]], grad_fn=<SoftmaxBackward>)
tensor([[[1., 1., 1., 1.]]], grad_fn=<SoftmaxBackward>)
tensor([[[1., 1., 1., 1.]]], grad_fn=<SoftmaxBackwa

KeyboardInterrupt: 

In [44]:
import numpy as np
import torch as th
import scipy.sparse as sp

a = th.rand(10,3)

# rowsum = np.array(a.sum(1))
# r_inv = np.power(rowsum, -1).flatten()
# r_inv[np.isinf(r_inv)] = 0.
# r_mat_inv = sp.diags(r_inv)
# mx = r_mat_inv.dot(a)
# print(mx)

a = np.array(a)
print(a)
x1 = []
x2 = []
for i in range(a.shape[1]):
    temp = (a[:, i] - np.min(a[:, i])) / (np.max(a[:, i]) - np.min(a[:, i]))
    x1.append(temp)

for i in range(a.shape[1]):
    temp = (a[:, i] - np.mean(a[:, i])) / np.std(a[:, i])
    x2.append(temp)

x = th.Tensor(x1)
print(x)
x = th.Tensor(x2)
print(x)


print('03_ok')

[[0.7750275  0.5118148  0.2948432 ]
 [0.753338   0.1481781  0.44358945]
 [0.00553626 0.15809679 0.57791334]
 [0.17234921 0.28322703 0.14579862]
 [0.6272144  0.01666093 0.46982068]
 [0.2781887  0.84367704 0.9976265 ]
 [0.90245086 0.4840855  0.882231  ]
 [0.40373337 0.39092463 0.33362412]
 [0.48373854 0.8461616  0.54425985]
 [0.23575747 0.895375   0.30632824]]
tensor([[0.8579, 0.8337, 0.0000, 0.1860, 0.6931, 0.3040, 1.0000, 0.4440, 0.5332,
         0.2567],
        [0.5635, 0.1497, 0.1610, 0.3034, 0.0000, 0.9412, 0.5319, 0.4259, 0.9440,
         1.0000],
        [0.1750, 0.3496, 0.5073, 0.0000, 0.3804, 1.0000, 0.8645, 0.2205, 0.4678,
         0.1885]])
tensor([[ 1.1109,  1.0335, -1.6351, -1.0398,  0.5834, -0.6621,  1.5656, -0.2141,
          0.0714, -0.8136],
        [ 0.1790, -1.0264, -0.9935, -0.5788, -1.4624,  1.2791,  0.0871, -0.2218,
          1.2873,  1.4504],
        [-0.8103, -0.2217,  0.3099, -1.4001, -0.1179,  1.9708,  1.5141, -0.6568,
          0.1767, -0.7648]])
03_ok
